### ISSUE TITLE
Files using docker on OS X

### ISSUE THREAD

**Issue by AnasGhrab** [Parisson/Telemeta#112]
Hi,

Telemeta works now on OS X using the docker and the dev branch. But : 

1. I can't read the demo files (it doesn't load)
2. I can't add files.

I'm using the login admin/admin. Is it  related to the access permissions in media ?

**Comment by yomguy** [comment]
I think we have trouble with default access rights on media (not easy to find a good solution between prod and dev use cases :/ ). @AnasGhrab can you try f933913 please ?

**Comment by AnasGhrab** [comment]
I still can't read the demo files, but I can add files and read them correctly.
