### ISSUE TITLE
Autorisations (chmod) du dossier tmp d'upload

### ISSUE THREAD

**Issue by AnasGhrab** [Parisson/Telemeta#131]
Après la mise à jour vers 1.6.3, en utilisant le docker, on a constaté une erreur 500 juste après l'upload d'un fichier. Le chmod du dossier tmp dans media était 644. Là il est 775 et on a plus ce problème. Quelle est la bonne configuration ?

**Comment by yomguy** [comment]
Oui 755 pour qu'un dossier soit accessible. Je vérifie que le mode est OK au 1er démarrage..

**Comment by yomguy** [comment]
Je confirme que le dossier prend bien les droits 755 au 1er upload.
