### ISSUE TITLE
Reindex content

### ISSUE THREAD

**Issue by AnasGhrab** [Parisson/Telemeta#134]
I would like to reindex the content. But in the docker : /srv/Telemeta/app, if I do : ```./manage.py update_index``` I get ```Unknown command: 'update_index'```

```haystack``` management has changed ?

**Comment by maths28** [comment]
It's not /srv/Telemeta/app but /srv/app. 
With this folder, the command is docker-compose run app /srv/app/manage.py update_index

**Comment by yomguy** [comment]
Hi all,

Thanks @maths28 for the response. 

Just to mention the command rebuilding the whole index in case it would be broken:

`docker-compose run app /srv/app/manage.py rebuild_index`
