### ISSUE TITLE
Server error 500 new archive

### ISSUE THREAD

**Issue by vince1992** [Parisson/Telemeta#138]
Hello,

I have an error 500 while I add a new audio file and I want to go to the page of this new archive.

On linux, I see this error :
`
app_1         | [pid: 338|app: 0|req: 5/29] 192.168.0.207 () {42 vars in 913 bytes} [Thu Aug 25 15:26:09 2016] GET /archives/collections/Web2Day/ => generated 2655 bytes in 87 msecs (HTTP/1.1 500) 4 headers in 253 bytes (1 switches on core 4)`

How can I resolve this problem ?

Thank you in advance. Cordially.

Vincent Leveque

**Comment by vince1992** [comment]
I finally solved my problem by reinstalling Debian and Telemeta.

**Comment by yomguy** [comment]
Great, I must say I was not able to reproduce the bug. So I think it was a pb of file access rights..
Cheers

**Comment by AnasGhrab** [comment]
I have a fresh new installation and I got this problem. I think it is a chmod problem... I remember that the first ```docker-compose up``` was done using ```sudo```..

**Comment by AnasGhrab** [comment]
Hmm.. the solution of vince1992 worked for me too. I had deleted docker images and it was ok.

**Comment by AnasGhrab** [comment]
Finally, my problem was this : https://github.com/Parisson/Telemeta/issues/156
