### ISSUE TITLE
Re-creating database ( Mysql )

### ISSUE THREAD

**Issue by lluc** [Parisson/Telemeta#148]
I've got a problem with the database during my developpement : I tried to change the structure/relation of field/table. But, It was not right.
So, I want to restore the initial strtucture of the database and then, make a _migrate --fake_.
But, I don't know how to restore the intial structure of the database  ( Mysql ).
I tried many ways ( docker-compose rm, ... etc .. ) , but the modified structure and the data of the database are always alive ...  :-(  :-1: 
How can I proceed ?
Thanks.

**Comment by thomasfillon** [comment]
Hi Luc,

I'm not sure to understand if you want to delete all the database files or just roll back to a previous migration state in the migrations history.

If you want to delete everything, all the mysql data are in the `data/mysql` subdirectory. You may need to use `sudo` : `sudo rm -r data/mysql/`

If you just want to go back to some previous migration state you can use something like that:
`docker-compose -f docker-compose.yml run app python manage.py  migrate 0034_auto__add_mediaitemidentifier__add_unique_mediaitemidentifier_identifi`

Warning : be sure to use the same `docker-compose` configuration file(s) that you use to launch Telemeta for example 

- `docker-compose up` -> `docker-compose run app python manage.py ...`, 
- `docker-compose -f  file1.yml -f file2.yml up` -> `docker-compose -f  file1.yml -f file2.yml run app python ...`

**Comment by lluc** [comment]
OK. Nice !
It was to destroy the currently database, and replace it with the original + migrations.
Thanks Thomas. :-)

**Comment by thomasfillon** [comment]
OK. Thank you for your feedback. Can we close this issue ?

**Comment by lluc** [comment]
Yes. :-)
