### ISSUE TITLE
Using locales in a fork

### ISSUE THREAD

**Issue by lluc** [Parisson/Telemeta#150]
I've made a _fork_ of Telemeta ( https://github.com/lluc/Telemeta/tree/mshs/telemeta ).
In this project, I want to modify some labels. E.g : _"missions"_ replace the name _"corpus"_.
I saw that there's a project to manage the locales ( https://github.com/Parisson/Telemeta-locales )

How to proceed ?

- made a _fork_ a the _locales_ project ?
- how integrate another _locales_ project ( a _fork_ ) ?
- or only make a _branch_ in a _locales_ project ?
- .....

Thanks,
Luc.

**Comment by yomguy** [comment]
Hi @lluc 
Yes, making your own branch inside Telemeta-locales is the right way.
Do you know how to update them afterwards?

**Comment by lluc** [comment]
No, how to update them afterwards? _Thanks_

**Comment by yomguy** [comment]
`docker-compose run app manage.py makemessages -a`

edit *.po files, then:

`docker-compose run app manage.py compilemessages`

**Comment by lluc** [comment]
It doesn't work.  :-(

```
Starting telemeta_search_1
Starting telemeta_data_1
Starting telemeta_broker_1
Starting telemeta_db_1
ERROR: Cannot start service app: b'Cannot start container 2ee5a9a00d1d10357c4efbfdf13cc969db580f9e7d65ca326b715b59e99fe443: [8] System error: exec: "manage.py": executable file not found in $PATH'

```

Why ?

**Comment by thomasfillon** [comment]
It seems you are not in the right directory 
`docker-compose run app pwd`should tell you where you are.

**Comment by lluc** [comment]
Result, only : 
```
Starting telemeta_broker_1
Starting telemeta_data_1
Starting telemeta_search_1
Starting telemeta_db_1
```

**Comment by thomasfillon** [comment]
The proper command is:
`docker-compose run app **python** manage.py makemessages -a`

edit *.po files, then:

`docker-compose run app  **python** manage.py compilemessages`

**Comment by thomasfillon** [comment]
I guess the command can be run outside the docker container but it should be better to use the same django version.

From docker-compose, the proper command is:

`docker-compose -f docker-compose.yml -f env/dev.yml run app sh -c "apt-get install -y gettext; cd /srv/src/telemeta; django-admin makemessages -a"`

edit *.po files, then:

`docker-compose -f docker-compose.yml -f env/dev.yml run app sh -c "apt-get install -y gettext; cd /srv/src/telemeta; django-admin compilemessages"`

**Comment by thomasfillon** [comment]
I would add the `gettext` executable in the docker image to remove the need to add `apt-get install -y gettext`

**Comment by thomasfillon** [comment]
I would add the `gettext` executable in the docker image to remove the need to add `apt-get install -y gettext`

**Comment by lluc** [comment]
This command line seems to works : 
`docker-compose -f docker-compose.yml -f env/dev.yml run app sh -c "apt-get install -y gettext; cd /srv/src/telemeta; django-admin compilemessages"`

Now I have to verified that the translated messages are OK.

**Comment by thomasfillon** [comment]
@lluc  Could we close this issue ?

**Comment by lluc** [comment]
Yes.
It's now OK : you have corrected some mistakes/errors from previous answers.
Thanks.
