### ISSUE TITLE
"Select all" button not working

### ISSUE THREAD

**Issue by Quint-e** [Parisson/Telemeta#151]
The "select all" button does not work. 
When clicking the checkbox nothing happens (i.e. no items get selected). 
Therefore we cannot select multiple items, collections or corpora in one go, which is very inconvenient when we need to select a large number of items.

**Comment by yomguy** [comment]
It works for me. Can you give me the domain, the page where you try to define the selection?

**Comment by Quint-e** [comment]
Here is one example: 
http://archives.crem-cnrs.fr/archives/collections/CNRSMH_I_2016_009/
The "select all" button does not work in the 'items' section.

**Comment by yomguy** [comment]
Indeed, it does NOT work :/
