### ISSUE TITLE
devbox_nginx_1 error while "docker-compose up" 

### ISSUE THREAD

**Issue by sone** [Parisson/Telemeta#154]
Hi,

I just cloned the DevBox as it is described and recommended at telemeta.org.
After "(sudo) docker-compose up" and after a lot of things are succesfully downloaded, I get an error as you can find below. I'm on Kubuntu 16.04 (with KXStudio).

"Status: Downloaded newer image for nginx:latest
Creating devbox_nginx_1
ERROR: oci runtime error: container_linux.go:247: starting container process caused "process_linux.go:359: container init caused \"rootfs_linux.go:54: mounting \\\"/home/username/Telemeta/DevBox/Telemeta/examples/deploy/nginx-app.conf\\\" to rootfs \\\"/var/lib/docker/aufs/mnt/e3a5c0d8a8e91421ca52cf0344b134a12beddd9ba0caaf1ada71552a00e163d0\\\" at \\\"/var/lib/docker/aufs/mnt/e3a5c0d8a8e91421ca52cf0344b134a12beddd9ba0caaf1ada71552a00e163d0/etc/nginx/conf.d/default.conf\\\" caused \\\"not a directory\\\"\""
: Are you trying to mount a directory onto a file (or vice-versa)? Check if the specified host path exists and is the expected type"

Best regards,
Johannes

**Comment by AnasGhrab** [comment]
These instructions are pretty old.. I think you should follow ones you find here : https://github.com/Parisson/Telemeta/

**Comment by sone** [comment]
Thank you very much for information! Thus I'll start again... 
To have updated information at telemeta.org and/or to have just a link to single source of information (github) at telemeta.org would be nice anyway.

**Comment by sone** [comment]
Happy day! I followed the instructions as provided here at github and Telemeta was up and running without any issues after a few minutes. Thank you very much!

**Comment by yomguy** [comment]
That's right, I've got to update the official web pages! I'm glad it's working for you now..
And thanks @AnasGhrab ;)
