### ISSUE TITLE
Serve media files through Nginx

### ISSUE THREAD

**Issue by thomasfillon** [Parisson/Telemeta#155]
This was done in Timeside : https://github.com/Parisson/TimeSide/commit/e23c8ae95866d0d2b2d54b70b0f5b6edae51b6d9

The idea is to serve media files through Nginx with `X-accel-redirect` header. 
Media files would then be serve as static files by Nginx but would be protected through regular Django permissions and authentication. 

See:

- https://wellfire.co/learn/nginx-django-x-accel-redirects/
- http://stackoverflow.com/questions/23301639/stream-music-with-byte-range-requests-with-django-nginx
- https://www.nginx.com/resources/wiki/start/topics/examples/x-accel/
- https://gist.github.com/bryanchow/1776202

The current Timeside implementation serves static files fine and enable **HTML5 support** !

TODO : 

- enable fallback when Nginx is not use (see https://gist.github.com/bryanchow/1776202)
- enable **streaming during on-the-fly transcoding** : this may be done through the `X-Accel-Buffering` header:
   - https://www.nginx.com/resources/wiki/start/topics/examples/x-accel/

> Sets the proxy buffering for this connection. **Setting this to “no” will allow unbuffered responses suitable for** Comet and **HTTP streaming applications.** Setting this to “yes” will allow the response to be cached.

   - http://serverfault.com/questions/482875/nginx-removes-content-length-header-for-chunked-content
   - http://nginx.org/en/docs/http/ngx_http_proxy_module.html#proxy_buffering

**Comment by yomguy** [comment]
Super inputs @thomasfillon ! I will try `X-Accel-Buffering` soon
