### ISSUE TITLE
Version 1.5 Install : No module named settings

### ISSUE THREAD

**Issue by AnasGhrab** [Parisson/Telemeta#16]
With the installation of Telemeta 1.5, I get this error 

Request Method: 	GET
Request URL: 	http://phonotheque.cmam.tn:8800/
Django Version: 	1.6.8
Exception Type: 	ImportError
Exception Value: 	

No module named settings

Exception Location: 	/usr/local/lib/python2.7/dist-packages/Telemeta-1.5-py2.7.egg/telemeta/views/pages.py in project_dir, line 53
Python Executable: 	/usr/bin/python
Python Version: 	2.7.3

The admin section works well, but I dont get the french language.

**Comment by yomguy** [comment]
Hi Anas,
I've never got this one, but 51e0d59 might fix this (packaged in https://github.com/Parisson/Telemeta/releases/tag/1.5.0rc5 )

The new version 1.5 also needs to initialize the *pages* and *locales* directories ?
So, for now, and for testing, I advise you checkout our dev branch and init those like this:

```
git clone https://github.com/Parisson/Telemeta.git
cd Telemeta
git checkout dev
git submodule foreach git fetch --tags
git submodule update --init --recursive
```

So you would get the available languages ;)

**Comment by AnasGhrab** [comment]
I followed those commands and cd in the sandbox example, syncdb and migrate, then I get the following : 
Environment:


Request Method: GET
Request URL: http://phonotheque.cmam.tn:8000/

Django Version: 1.6.8
Python Version: 2.7.3
Installed Applications:
('django.contrib.auth',
 'django.contrib.contenttypes',
 'django.contrib.sessions',
 'django.contrib.sites',
 'django.contrib.messages',
 'suit',
 'django.contrib.admin',
 'django.contrib.staticfiles',
 'django_extensions',
 'telemeta',
 'timeside.player',
 'jsonrpc',
 'south',
 'sorl.thumbnail',
 'timezones',
 'jqchat',
 'ipauth',
 'extra_views',
 'debug_toolbar',
 'bootstrap3',
 'bootstrap_pagination',
 'googletools')
Installed Middleware:
('django.middleware.common.CommonMiddleware',
 'django.contrib.sessions.middleware.SessionMiddleware',
 'django.middleware.csrf.CsrfViewMiddleware',
 'django.contrib.auth.middleware.AuthenticationMiddleware',
 'django.contrib.messages.middleware.MessageMiddleware',
 'django.middleware.locale.LocaleMiddleware')


Traceback:
File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py" in get_response
  112.                     response = wrapped_callback(request, *callback_args, **callback_kwargs)
File "/usr/local/lib/python2.7/dist-packages/Telemeta-1.5-py2.7.egg/telemeta/views/home.py" in home
  73.                     'page_content': pages.get_page_content(request, 'home', ignore_slash_issue=True),
File "/usr/local/lib/python2.7/dist-packages/Telemeta-1.5-py2.7.egg/telemeta/views/pages.py" in get_page_content
  106.     userroot = os.path.join(project_dir(), 'telemeta-pages')
File "/usr/local/lib/python2.7/dist-packages/Telemeta-1.5-py2.7.egg/telemeta/views/pages.py" in project_dir
  54.     if '__init__.py' in settings_mod.__file__:
File "/usr/local/lib/python2.7/dist-packages/django/conf/__init__.py" in __getattr__
  55.         return getattr(self._wrapped, name)

Exception Type: AttributeError at /
Exception Value: 'Settings' object has no attribute '__file__'

**Comment by yomguy** [comment]
Mmm sorry, the first code was ok. Then ba10ccf update it..
Can you please init the *pages* and *locales* dirs?
