### ISSUE TITLE
Installation of 1.5 on OS X Yosemite

### ISSUE THREAD

**Issue by AnasGhrab** [Parisson/Telemeta#17]
The installation was ok. With the sandbox example, launching the server gives 

MacBook-Pro-de-Anas:sandbox anas$ ./manage.py runserver
/usr/local/lib/python2.7/site-packages/sorl/thumbnail/helpers.py:5: DeprecationWarning: django.utils.simplejson is deprecated; use json instead.
  from django.utils import simplejson

** Message: pygobject_register_sinkfunc is deprecated (GstObject)
/usr/local/lib/python2.7/site-packages/sorl/thumbnail/helpers.py:5: DeprecationWarning: django.utils.simplejson is deprecated; use json instead.
  from django.utils import simplejson

** Message: pygobject_register_sinkfunc is deprecated (GstObject)
Validating models...

0 errors found
January 04, 2015 - 15:25:30
Django version 1.6.8, using settings 'settings'
Starting development server at http://127.0.0.1:8000/
Quit the server with CONTROL-C.

========================================

When I go to the web site, it shows

  File "/usr/local/Cellar/python/2.7.8_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/django_jqchat-0.2-py2.7.egg/jqchat/urls.py", line 3, in <module>
    from django.conf.urls.defaults import *
ImportError: No module named defaults

**Comment by AnasGhrab** [comment]
After removing .defaults from the file from File "/usr/local/Cellar/python/2.7.8_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/django_jqchat-0.2-py2.7.egg/jqchat/urls.py"

I get the error

TypeError at /

'NoneType' object is not iterable

Request Method: 	GET
Request URL: 	http://127.0.0.1:8000/
Django Version: 	1.6.8
Exception Type: 	TypeError
Exception Value: 	

'NoneType' object is not iterable

Exception Location: 	/usr/local/Cellar/python/2.7.8_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/Telemeta-1.5-py2.7.egg/telemeta/templatetags/telemeta_utils.py in render_flatpage, line 286
Python Executable: 	/usr/local/opt/python/bin/python2.7
Python Version: 	2.7.8

Same problem as the installation on Debian.

**Comment by yomguy** [comment]
(Almost) congrats for this install!!
I'm afraid, the jqchat version was to old on pypi :( I'm using this one in fact:
https://github.com/yomguy/django-jqchat

But, I've just update the pypi package to 0.3. Could you try with the new one ?
```
sudo pip install -U django-jqchat
```

**Comment by yomguy** [comment]
Any good news ?

**Comment by yomguy** [comment]
Now obsolete thanks to th docker-compose sandbox
