### ISSUE TITLE
Fix media access rights with `chown`

### ISSUE THREAD

**Issue by thomasfillon** [Parisson/Telemeta#176]
The current ways to fix media access right for user www-data is the following: 
https://github.com/Parisson/Telemeta/blob/master/app/scripts/app.sh#L41
```
# fix media access rights
chown www-data:www-data $media
for dir in $(ls $media); do
    if [ ! $(stat -c %U $media/$dir) = 'www-data' ]; then
        chown www-data:www-data $media/$dir
    fi
done
```

It does not cover sub-sub-directory like `/srv/media/items/tests`.

As discussed with @yomguy using `chown -R www-data:www-data $media/$dir` may take too much time in production.

The following may be relevant:
`find $media -type d -exec chown www-data:www-data  {} \;`
which would find all subdirectories abd change permissions only on those directories.
Alternatively,
`find $media -type d -user root -exec chown www-data:www-data  {} \;`
or 
`find $media -user root -exec chown www-data:www-data  {} \;`
will only select directories (resp. files) that belong to user _root_
Time consumption of these should be tested .

**Comment by yomguy** [comment]
Excellent solution ! We only need it for directories as the files are never modified by django

**Comment by thomasfillon** [comment]
I would choose  
`find $media -type d -exec chown www-data:www-data {} \;`

are you ok with that ?
