### ISSUE TITLE
[Dj 1.8] Collection : can't delete.

### ISSUE THREAD

**Issue by lluc** [Parisson/Telemeta#179]
In our branch [mshs], we can't delete a collection.
After having analyzed the source code ( <https://github.com/Parisson/Telemeta/blob/feature/dj1.8/telemeta/models/core.py#L80> ), it seems that the new meta-model API wasn't considered in the Dj1.8's migration... :-(

Here's the link to the reference documentation : https://docs.djangoproject.com/en/1.8/ref/models/meta/
See _Migrating from the old API_.

**Comment by thomasfillon** [comment]
@lluc  Thanks for the issue and the link to migration guidelines.
