### ISSUE TITLE
Install on Debian, sandbox example

### ISSUE THREAD

**Issue by AnasGhrab** [Parisson/Telemeta#18]
Running the server using the sanbox example, similarly to the installation on OS X Yosemite, I get 

TypeError at /

'NoneType' object is not iterable

Request Method: 	GET
Request URL: 	http://phonotheque.cmam.tn:8800/
Django Version: 	1.6.8
Exception Type: 	TypeError
Exception Value: 	

'NoneType' object is not iterable

Exception Location: 	/usr/local/lib/python2.7/dist-packages/Telemeta-1.5-py2.7.egg/telemeta/templatetags/telemeta_utils.py in render_flatpage, line 286
Python Executable: 	/usr/bin/python
Python Version: 	2.7.3

**Comment by yomguy** [comment]
render_flatpage also needs the *pages* directory to be initialize.
Sorry for that, *pages* and *locales* have been split as git submodules recently so the new doc and the pypi package need to be published ;)

**Comment by AnasGhrab** [comment]
« init the pages and locales dirs »

So.. how to do that ? :)

**Comment by yomguy** [comment]
like explained in #16 
```
git clone https://github.com/Parisson/Telemeta.git
cd Telemeta
git checkout dev
git submodule foreach git fetch --tags
git submodule update --init --recursive
```

;)

**Comment by yomguy** [comment]
And maybe
```
sudo python setup.py install
```
if needed

**Comment by AnasGhrab** [comment]
All right now with the sandbox. Thank you ! :)

I'll try strating a project and keep you informed.

**Comment by yomguy** [comment]
Great!
