### ISSUE TITLE
Display pb on advanced search page for 1.6.4 CREM

### ISSUE THREAD

**Issue by aude-crem** [Parisson/Telemeta#182]
Bonjour, il semble que suite à la dernière mise à jour du telemeta-CREM, il y a un problème d'affichage sur la page de recherche avancée, cf. capture d'écran en PJ (sur Firefox), merci, aude
![rechercheavancee_firefox](https://user-images.githubusercontent.com/22094109/27854877-b586043a-6168-11e7-8ae9-280b5881786d.png)

**Comment by thomasfillon** [comment]
Hi Aude,

Thank you.
The error seems to be due to a recent upgrade of some Javascript librairies.
We need to keep with previous versions or to update the code.
