### ISSUE TITLE
Video files are not accessible though the (now secured) file server

### ISSUE THREAD

**Issue by aude-crem** [Parisson/Telemeta#183]
Bonjour, il semble que depuis la dernière mise à jour, il y a un problème avec la lecture des fichiers vidéo, le lecteur vidéo affiche le message "Aucune vidéo dont le format ou le type MIME est géré n'a été trouvée", exemples d'items vidéo (en webm et en mp4) :
http://archives.crem-cnrs.fr/archives/items/CNRSMH_E_2011_027_001_01/
http://archives.crem-cnrs.fr/archives/items/CNRSMH_I_2010_004_001_01/
merci, aude

**Comment by yomguy** [comment]
Fixé avec les dernières modifications de configuration du serveur web.
