### ISSUE TITLE
Problem editing Fond entity and assigning Corpus

### ISSUE THREAD

**Issue by amotl** [Parisson/Telemeta#188]
We found another two minor glitches leading to the rejection of the save operation on main entities:
- When trying to amend the "Title" field of a Fond which doesn't have an assignment of a Corpus yet, Telemeta will reject the save operation saying "Please select an item in the list." in the "Available Corpus" chooser.
- The same thing happens when actually assigning a Corpus by putting it into the "Chosen Corpus" list and there's no other Corpus entity left in the "Available Corpus" chooser to be selected.

The same occurs for a Corpus without an assignment of a Collection and probably for any turtles all the way down. We also used the Django admin as a workaround here.

We are running Telemeta from the master branch (v1.6.4).

**Comment by yomguy** [comment]
Thanks for the review @amotl 
fixed in the master and dev branch ;)

**Comment by amotl** [comment]
Seems to work on the "dev" branch now. Thanks Guillaume for addressing this issue!
