### ISSUE TITLE
UTF-8 problem (arabic and latin special characters)

### ISSUE THREAD

**Issue by AnasGhrab** [Parisson/Telemeta#19]
Writing in arabic gives me : ?????????

I have other mysql databases and django applications on the server, and there are no encoding problems...

http://phonotheque.cmam.tn

**Comment by AnasGhrab** [comment]
While I tried to add an alias in Arabic for a place I got this :+1: 

 File "/usr/local/lib/python2.7/dist-packages/django/db/backends/mysql/base.py", line 124, in execute
   return self.cursor.execute(query, args)

 File "/usr/lib/python2.7/dist-packages/MySQLdb/cursors.py", line 174, in execute

 File "/usr/lib/python2.7/dist-packages/MySQLdb/connections.py", line 36, in defaulterrorhandler

OperationalError: (1267, "Illegal mix of collations (latin1_swedish_ci,IMPLICIT) and (utf8_general_ci,COERCIBLE) for operation '='")
OperationalError: (1267, "Illegal mix of collations (latin1_swedish_ci,IMPLICIT) and (utf8_general_ci,COERCIBLE) for operation '='")

Is it the same problem and I relation with ?
https://gist.github.com/philippeowagner/6530635

I'm looking forward..

**Comment by yomguy** [comment]
I think django would start UTF-8 databases by default. If that's not your case, you can try with this option in DATABASES['default'] :
```
'OPTIONS'  : { 'init_command' : 'SET storage_engine=MyISAM,character_set_connection=utf8,collation_connection=utf8_unicode_ci', },
```

Note: I have some pb with InnoDB scheme with telemeta models.  Help is welcome!

**Comment by AnasGhrab** [comment]
Nothing changed using the OPTIONS.

**Comment by yomguy** [comment]
Mmm, sorry, I never wrote arabic yet :)
Where did you test the characters? In a collection or item form?

**Comment by AnasGhrab** [comment]
Everywhere...

But when I test on the CREM website, it works...

The project I installed is a copy of the sanbox.. with nothing changed...

**Comment by yomguy** [comment]
OK, seems a SQL pb then.
Did you start your DB with utf8_general_ci?
http://stackoverflow.com/questions/1073295/django-character-set-with-mysql-weirdness

**Comment by AnasGhrab** [comment]
Yes ! Its ok now ;)

**Comment by yomguy** [comment]
great!
