### ISSUE TITLE
Arabic language disposition hide language selector

### ISSUE THREAD

**Issue by thomasfillon** [Parisson/Telemeta#190]
When selecting the arabic language the language selector stay on the right and is then hide by the Home Tab.

copy to @AnasGhrab 

Note: the selector is not completely hidden and slightly appears between the first two tabs on the right. It can then be used to set another language. ;)

**Comment by AnasGhrab** [comment]
Fixed here : https://github.com/AnasGhrab/Telemeta/commit/414adc2213b2fa99341c9caaa1e4cefbae3794e3
