### ISSUE TITLE
Database Upgrade

### ISSUE THREAD

**Issue by AnasGhrab** [Parisson/Telemeta#199]
What is the procedure to upgrade a database to the last version, from 1.6.0 ? Is possible to that after a Backup/Restore using ```docker-compose run db /srv/scripts/sql/restore_db.sh```?

**Comment by yomguy** [comment]
Hi Anas!

1. backup your DB : `docker-compose run db /srv/scripts/sql/backup_db.sh`
2. upgrade : `git pull && git submodule update --init --remote`
3. migrate : `docker-compose run app python manage.py migrate`
4. collect (in production) : `docker-compose run app python manage.py collectstatic`

Please try on a sandbox instance before doing this in production ;)

**Comment by AnasGhrab** [comment]
Hi Guillaume,

I git this : 
```
Starting telemeta_data_1 ... 
Starting telemeta_search_1 ... 
Starting telemeta_data_1 ... done
Starting telemeta_db_1 ... done
Unknown command: 'migrate'
Type 'manage.py help' for usage.
```

**Comment by AnasGhrab** [comment]
Do I need to uncomment south in settings.py ?
