### ISSUE TITLE
Videoplayer for telemeta

### ISSUE THREAD

**Issue by ky1357** [Parisson/Telemeta#200]
Hello.
I do like to know if videoplayer for telemeta (not only playing sound on mp4, webm, flv etc. but also moving image) is working.
We'd like to show moving images as well if possible. 

---------------------
<head>
 
    <script src="/static/SoundManager2/script/soundmanager2-nodebug-jsmin.js" type="text/javascript"></script>
    <script src="/static/timeside/js/timeside.js" type="text/javascript"></script>
    <script src="/static/telemeta/js/playerLoader.js" type="text/javascript"></script>
    <script src="/static/telemeta/js/divmarker.js" type="text/javascript"></script>
 

<script type="text/javascript">
    
     
        //initializing soundManager default properties
        soundManager.flashVersion = 9;
        soundManager.url = "/static/SoundManager2/swf/";
        soundManager.debugMode = false;
        soundManager.useHTML5Audio = true;
        soundManager.preferFlash = false;
        soundManager.html5PollingInterval = 50;

        //initializing the visualizers to be passed to the player
        
        var visualizers = {};
        
            visualizers["Waveform spectral"] = "/archives/items/CNRSMH_I_2017_025_001_01/visualize/waveform_centroid/WIDTHxHEIGHT/";
        
            visualizers["Pitch"] = "/archives/items/CNRSMH_I_2017_025_001_01/visualize/grapher_aubio_pitch/WIDTHxHEIGHT/";
        
            visualizers["Onset detection"] = "/archives/items/CNRSMH_I_2017_025_001_01/visualize/grapher_onset_detection_function/WIDTHxHEIGHT/";
        
            visualizers["Spectrogram Log"] = "/archives/items/CNRSMH_I_2017_025_001_01/visualize/spectrogram_log/WIDTHxHEIGHT/";
        
            visualizers["Spectrogram Lin"] = "/archives/items/CNRSMH_I_2017_025_001_01/visualize/spectrogram_lin/WIDTHxHEIGHT/";
        
            visualizers["Waveform simple"] = "/archives/items/CNRSMH_I_2017_025_001_01/visualize/waveform_simple/WIDTHxHEIGHT/";
        
            visualizers["Contour black"] = "/archives/items/CNRSMH_I_2017_025_001_01/visualize/waveform_contour_black/WIDTHxHEIGHT/";
        
            visualizers["Contour white"] = "/archives/items/CNRSMH_I_2017_025_001_01/visualize/waveform_contour_white/WIDTHxHEIGHT/";
        
            visualizers["Waveform transparent"] = "/archives/items/CNRSMH_I_2017_025_001_01/visualize/waveform_transparent/WIDTHxHEIGHT/";
        
            visualizers["Monody/polyphony detection"] = "/archives/items/CNRSMH_I_2017_025_001_01/visualize/grapher_irit_monopoly_segments/WIDTHxHEIGHT/";
        
            visualizers["Music detection"] = "/archives/items/CNRSMH_I_2017_025_001_01/visualize/grapher_irit_music_sln_segments/WIDTHxHEIGHT/";
        
            visualizers["Tape start detection"] = "/archives/items/CNRSMH_I_2017_025_001_01/visualize/grapher_irit_startseg/WIDTHxHEIGHT/";
        
            visualizers["Speech detection (syllabic rate)"] = "/archives/items/CNRSMH_I_2017_025_001_01/visualize/grapher_irit_speech_4hz_segments_median/WIDTHxHEIGHT/";
        
            visualizers["Speech detection (signal diversity)"] = "/archives/items/CNRSMH_I_2017_025_001_01/visualize/grapher_irit_speech_entropy_segments/WIDTHxHEIGHT/";
        
            visualizers["Singing voice detection"] = "/archives/items/CNRSMH_I_2017_025_001_01/visualize/grapher_labri_singing/WIDTHxHEIGHT/";
        
        

        
           loadPlayer('/archives/items/CNRSMH_I_2017_025_001_01/analyze/xml/',
             "/archives/items/download/CNRSMH_I_2017_025_001_01.mp3", undefined, '66155', visualizers,
             CURRENT_USER_NAME,  //undefined if !user.is_authenticated
             false); //false because not superuser
        
     
    
    //playlists:
    
        
        	
        	            playlistUtils.addPlaylist('Bolivie','152328036591644719');
        	
        
            jQuery(window).ready(function(){
                var anchor = jQuery('#_add_to_playlist');
                if(anchor.length){
                    anchor.unbind('click').click(function(){
                        playlistUtils.showAddResourceToPlaylist(anchor,'item','66155',gettrans('item added to the selected playlist'));
                        //playlistUtils.showAddResourceToPlaylist(anchor,'item','66155');
                        return false;
                    });
                }
                playlistUtils.messageOk();
            });
    
</script>

<script src="/static/video.js/dist/video.min.js" ></script>
<link href="/static/video.js/dist/video-js.min.css" rel="stylesheet">

</head>

**Comment by yomguy** [comment]
Hi,
The current video player does not expect any image, but maybe we could adapt it.
What do you mean by "moving images"? GIF or equivalent format?

**Comment by josimonnot** [comment]
Hi,

The video player doesn't work: we have only the sound from the video files.
J

**Comment by josimonnot** [comment]
see:
http://archives.crem-cnrs.fr/archives/items/CNRSMH_I_2017_022_001_01/
"Aucune vidéo ... n'a été trouvée"

**Comment by yomguy** [comment]
@ky1357 WebM and MP4 are the only web compatible formats. I advise WebM by default as the open source one. At the end, the <video> player need both for being able to playback on any browser.
https://developer.mozilla.org/en-US/docs/Web/HTML/Supported_media_formats

Telemeta 2.0 will include a video transcoder.
