### ISSUE TITLE
Issue with restore db Telemeta 1.7

### ISSUE THREAD

**Issue by DafneStar** [Parisson/Telemeta#211]
Can I restore a backup database made in 1.6.3  in a 1.7 version?

When I run restore_db.sh command, get this error:

`ERROR 1215 (HY000) at line 29: Cannot add foreign key constraint.`

But in sql file line 29 is:

`CREATE TABLE acquisition_modes (`

And I already comment all foreign constraints lines to test. 

Thanks.

**Comment by yomguy** [comment]
Hi @DafneStar 
Can you please check you have mysql:5 in your docker-compose.yml file?

**Comment by DafneStar** [comment]
I'm not sure now, I solved the problem by creating a backup database with backup command after upgrading our system. After that restore command worked well.

Thanks for your attention.
