### ISSUE TITLE
Demo doesn't work

### ISSUE THREAD

**Issue by ArturFormella** [Parisson/Telemeta#224]
Hello!
A can't login into demo site:
http://demo.telemeta.org/accounts/login/

```
Demo
http://demo.telemeta.org
        login: admin
        password: admin
```

**Comment by yomguy** [comment]
Hi @ArturFormella 
Sorry for that. It is now fixed.
G

**Comment by ArturFormella** [comment]
I'm sorry to write but it still doesn't work

**Comment by yomguy** [comment]
@ArturFormella sorry, I had put demo:demo, now admin:admin is OK!
