### ISSUE TITLE
Error on installation: The authenticity of host github.com can't be established.

### ISSUE THREAD

**Issue by DafneStar** [Parisson/Telemeta#233]
I made a new installation on both operating systems, Ubuntu 20.04 and CentOS 7.5 using the most recent docker and docker-compose versions. When I ran `git clone --recursive https://github.com/Parisson/Telemeta.git`
 I got:
 
`# git clone --recursive https://github.com/Parisson/Telemeta.git
Cloning into 'Telemeta'...
remote: Enumerating objects: 449, done.
remote: Counting objects: 100% (449/449), done.
remote: Compressing objects: 100% (237/237), done.
remote: Total 36016 (delta 341), reused 272 (delta 211), pack-reused 35567
Receiving objects: 100% (36016/36016), 30.34 MiB | 2.79 MiB/s, done.
Resolving deltas: 100% (26274/26274), done.
Submodule 'lib/TimeSide' (https://github.com/Parisson/TimeSide.git) registered for path 'lib/TimeSide'
Submodule 'telemeta/locale' (https://github.com/Parisson/Telemeta-locales.git) registered for path 'telemeta/locale'
Submodule 'telemeta/pages' (https://github.com/Parisson/Telemeta-pages.git) registered for path 'telemeta/pages'
Cloning into '/home/Telemeta/lib/TimeSide'...
remote: Enumerating objects: 71, done.
remote: Counting objects: 100% (71/71), done.
remote: Compressing objects: 100% (59/59), done.
remote: Total 22240 (delta 32), reused 28 (delta 12), pack-reused 22169
Receiving objects: 100% (22240/22240), 19.24 MiB | 2.78 MiB/s, done.
Resolving deltas: 100% (15007/15007), done.
Cloning into '/home/Telemeta/telemeta/locale'...
remote: Enumerating objects: 2571, done.
remote: Total 2571 (delta 0), reused 0 (delta 0), pack-reused 2571
Receiving objects: 100% (2571/2571), 2.07 MiB | 3.39 MiB/s, done.
Resolving deltas: 100% (1276/1276), done.
Cloning into '/home/Telemeta/telemeta/pages'...
remote: Enumerating objects: 2551, done.
remote: Total 2551 (delta 0), reused 0 (delta 0), pack-reused 2551
Receiving objects: 100% (2551/2551), 1.95 MiB | 2.47 MiB/s, done.
Resolving deltas: 100% (1294/1294), done.
Submodule path 'lib/TimeSide': checked out '932b7fab9fc8daed4b3ccab30c72ef207c88ef9e'
Submodule 'bin/install' (git@github.com:yomguy/docker-composition-installer.git) registered for path 'lib/TimeSide/bin/install'
Cloning into '/home/Telemeta/lib/TimeSide/bin/install'...
The authenticity of host 'github.com (140.82.112.4)' can't be established.
RSA key fingerprint is SHA256:nThbg6kXUpJWGl7E1IGOCspRomTxdCARLviKw6E5SY8.
Are you sure you want to continue connecting (yes/no/[fingerprint])? yes
Warning: Permanently added 'github.com,140.82.112.4' (RSA) to the list of known hosts.
git@github.com: Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
fatal: clone of 'git@github.com:yomguy/docker-composition-installer.git' into submodule path '/home/Telemeta/lib/TimeSide/bin/install' failed
Failed to clone 'bin/install'. Retry scheduled
Cloning into '/home/Telemeta/lib/TimeSide/bin/install'...
git@github.com: Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
fatal: clone of 'git@github.com:yomguy/docker-composition-installer.git' into submodule path '/home/Telemeta/lib/TimeSide/bin/install' failed
Failed to clone 'bin/install' a second time, aborting
Submodule path 'telemeta/locale': checked out 'a2a9b18a25bfc47a1c19974ed6bc1fde23f92448'
Submodule path 'telemeta/pages': checked out '6bd28050dc7e96a8a226ea928a8e7b09b130be93'
Failed to recurse into submodule path 'lib/TimeSide'
#
`
When I run docker-compose up, the system never ends to get up.

Is there another way to clone the project?
What am I doing wrong?  Tnx

**Comment by yomguy** [comment]
Hi @DafneStar !
I have pushed a fix for this. 
You can now `git pull ; git submodule update --remote --init` and then retry.

**Comment by ghost** [comment]
It works, tnx!!
