### ISSUE TITLE
error: Django 1.6.10 is installed but django==1.6.8 is required by set(['timeside'])

### ISSUE THREAD

**Issue by AnasGhrab** [Parisson/Telemeta#25]
After a new git pull of Telemeta and TimeSide, I get this error : 

error: Django 1.6.10 is installed but django==1.6.8 is required by set(['timeside'])

it seems that

sudo python setup.py install

installs Django 1.6.10

**Comment by thomasfillon** [comment]
Hi Anas,
Thank for the feedback. 
I think we need to update the requirements in TimeSide to match Django==1.6.10.

**Comment by yomguy** [comment]
Done and the TimeSide 0.7.1 has been released to fix the install ;)
