### ISSUE TITLE
Not possible to change the user password

### ISSUE THREAD

**Issue by liofeu** [Parisson/Telemeta#30]
In my telemeta user profile, if I click on the button "Change password", the following error is displayed :

NoReverseMatch at /accounts/password_change/
Reverse for 'password_change_done' with arguments '()' and keyword arguments '{}' not found. 0 pattern(s) tried: []

**Comment by yomguy** [comment]
Indeed :( Thanks Lionel.

**Comment by AnasGhrab** [comment]
I still have this problem, even with the version 1.5.1.
