### ISSUE TITLE
Personnalisation des pages

### ISSUE THREAD

**Issue by AnasGhrab** [Parisson/Telemeta#34]
Les indications de l'install concernant les sous-modules sont les suivantes : 

git submodule foreach git fetch --tags
git submodule update --init --recursive

Afin d'avoir des pages personnalisées, comment faire pour que le sub-module pages soit : 

https://github.com/AnasGhrab/Telemeta-pages

Merci,

**Comment by yomguy** [comment]
Qqchose comme :
```
cd telemeta/pages
git remote add anas https://github.com/AnasGhrab/Telemeta-pages
git pull anas master
git checkout anas/master
```
?

**Comment by AnasGhrab** [comment]
Ça marche bien; merci :)

Cependant, si les changements dans le dossier pages/fr/ sont pris en considération, ce n'est pas le cas de ceux dans pages/ar_TN. J'ai une erreur 500 sur la page d'accueil quand je mets la langue arabe.

**Comment by yomguy** [comment]
Tu peux voir les logs du serveur web ?

**Comment by AnasGhrab** [comment]
Oui

**Comment by AnasGhrab** [comment]
En fait j'ai ça comme erreur : 
\ File "/usr/local/lib/python2.7/dist-packages/Telemeta-1.5.2-py2.7.egg/telemeta/templatetags/telemeta_utils.py", line 286, in render_flatpage
   for line in content:

TypeError: 'NoneType' object is not iterable

et dans les logs j'ai ça quand c'est l'arabe : 
[Sun Feb 22 14:14:39 2015] [debug] mod_deflate.c(700): [client 197.27.53.51] Zlib: Compressed 2662 to 1170 : URL /

et ça quand c'est en français : 

[Sun Feb 22 14:16:11 2015] [debug] mod_deflate.c(700): [client 197.27.53.51] Zlib: Compressed 23165 to 5716 : URL /

**Comment by yomguy** [comment]
Il se peut que le parser render_flatpage bug avec les caractères arabes... Je vais vérifier.
