### ISSUE TITLE
Media Item Related provoque erreur 500

### ISSUE THREAD

**Issue by AnasGhrab** [Parisson/Telemeta#35]
Le formulaire « Médias Associés » dans Item provoque une erreur 500 si le champ Title n'est pas renseigné et l'Item devient inaccessible. Il devrait faire la vérification avant l'enregistrement. L'erreur donnée est : 

 File "/usr/local/lib/python2.7/dist-packages/django/db/models/fields/files.py", line 41, in _require_file
   raise ValueError("The '%s' attribute has no file associated with it." % self.field.name)

ValueError: The 'file' attribute has no file associated with it.

**Comment by yomguy** [comment]
Je n'arrive pas à reproduire, tu peux réessayer avec la dernière branche dev STP ?

**Comment by yomguy** [comment]
Salut Anas,
Peux-tu réessayer STP ?

**Comment by yomguy** [comment]
Il me semble que c'est fixé. Merci de fermer si OK.

**Comment by AnasGhrab** [comment]
Oui, avec la 1.6, cette erreur est partie.
