### ISSUE TITLE
Installation on Mac OS X Mavericks with Homebrew

### ISSUE THREAD

**Issue by sone** [Parisson/Telemeta#4]
Hello,

first of all, thank you very very much for this software! - it looks so good and I've been looking around for something like that for years. It was hard to find. If you would have a community forum or something like that I would like post texts like this one there...

I'm trying to install Telemeta on Mac OS 10.6.8
Has anybody had success with it? Somebody already running Telemeta on OS X?
Honestly I'm not so succesfull. Following these instructions:
https://github.com/yomguy/Telemeta/blob/master/INSTALL.rst
I noticed, even with Macports I cannot install all dependencies.
It would be very nice if a list could be provided with all the needed Python packages listed
with names as they are listed here: http://pypi.python.org/pypi
Because it is not easy to find out which similiar Python package could be used on other platforms. 
Some packages are Debian specific - python-xml as an example.

Related to Macports I've found a few of the the needed packages, but not all:

python-ctypes / ?
python-dev / ?
python-django / py27-django
python-django-registration / ?
python-django-south / py27-south?
python-docutils / py27-docutils
python-gobject / py27-gobject
python-gst0.10 / py27-gst-python
python-imaging / py27-pil
python-libxml2 / py27-libxml2
python-lxml / py27-lxml
python-numpy / py27-numpy
python-mutagen / py27-mutagen
python-mysqldb / py27-mysql
python-scipy / py27-scipy
python-setuptools / ?
python-support / ?
python-xml / ?

Best regards,
Johannes

**Comment by yomguy** [comment]
Some good news in #17

**Comment by yomguy** [comment]
Now obsolete thanks to the docker based sandbox.
