### ISSUE TITLE
Playlist edit window is buggy

### ISSUE THREAD

**Issue by yomguy** [Parisson/Telemeta#44]
- [x] apostrop char is not displayed well
- [x] long description is hidden by drag rulers
- [x] replace the current popup by a bootstrap modal one (as done for the "Share button")

**Comment by ThomasBalastegui** [comment]
I encounter some difficulties :
- making my bootstrap modal to communicate with the JavaScript part
- sending the variables Title and Description

**Comment by yomguy** [comment]
Hi @ThomasBalastegui 

1. did you try to trigger the modal popup from the `playlistUtils.showAdd` method ? https://github.com/Parisson/Telemeta/blob/dev/telemeta/static/telemeta/js/playlist.js#L61
2. the current methods `addPlaylist` and `addEditPlaylist` should do the job out of the box if the two  data fields are well parsed

Don't hesitate to push your current state to you repo - even if broken - so that we can see/patch the stuff.. ;)
