### ISSUE TITLE
Défaut balise date

### ISSUE THREAD

**Issue by josimonnot** [Parisson/Telemeta#52]
Dans l'export Dublin Core, il y a des balises incomplètes comme la balise fermante du champ "Date" est incomplète. 
Par exemple sur cette notice il y a un 1er champ titre renseigné et en suivant une 2ème balise titre vide, idem pour la date :
http://archives.crem-cnrs.fr/oai/?verb=GetRecord&identifier=:crem-cnrs:items:3829&metadataPrefix=oai_dc

Merci

**Comment by yomguy** [comment]
OK, je check, merci ;)

**Comment by yomguy** [comment]
Cela pose-t-il un pb pour les moissonneuses et autres parsers de traiter un champ vide ?

**Comment by josimonnot** [comment]
Oui c'est problématique pour le champ date pour isidore...

2015-04-21 22:02 GMT+02:00 Guillaume Pellerin <notifications@github.com>:

> Cela pose-t-il un pb pour les moissonneuses et autres parsers de traiter
> un champ vide ?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Parisson/Telemeta/issues/52#issuecomment-94920997>.
>



-- 
Joséphine Simonnot
Ingénieur de recherche
Centre de Recherche en Ethnomusicologie
(CREM - LESC UMR 7186 CNRS)
MAE - 21, allée de l'Université
92023 Nanterre cedex
Tel. : 01.46.69.26.66

**Comment by yomguy** [comment]
Fixed in ddab456f9a08bd1c91060cbe6943fa097989ffbb
