### ISSUE TITLE
Windows install

### ISSUE THREAD

**Issue by dianakaal** [Parisson/Telemeta#61]
Hello,

I need a system such as Telemeta to run on windows. 
In INSTALL.rst it mentions that Win platforms aren't officially supported, but possible. What does that mean? And what do I have to do to make it work? If you can give some pointers and then I can figure it out. I'm a web developer so hopefully my knowledge will be enough for this.
Thanks!
-Diana

**Comment by yomguy** [comment]
Hi Diana,

The next release of Telemeta coming in a few days will introduce a new install procedure based on docker which will make it compatible with windows.

For now, and as a developer, you can grab and start it with our DevBox:
https://github.com/Parisson/DevBox

Please give us some feedback if any trouble (it has not been tested so much on Windows). Thanks!
Guillaume

**Comment by yomguy** [comment]
Hi @dianakaal 
Did you try our DevBox?

**Comment by dianakaal** [comment]
Hi!

Unfortunately I haven't yet. I've been stuck on another project so didn't
have time. I'm also quite new to Python so am worried this might be a bit
out of my league until I do some studying on Python. Perhaps it is easy to
grasp and I am just panicking for nothing.

However if I get around to working on this then I will let you know!

Diana

**Comment by yomguy** [comment]
No worries, thanks ;)

**Comment by yomguy** [comment]
Telemeta is now available on Windows via Docker QuickStart Terminal
