### ISSUE TITLE
ValueError: invalid literal for int() with base 10

### ISSUE THREAD

**Issue by AnasGhrab** [Parisson/Telemeta#64]
I think that this error comes when we change the item's code : 

```
File "/usr/local/lib/python2.7/dist-packages/Django-1.6.10-py2.7.egg/django/db/models/fields/__init__.py", line 369, in get_prep_lookup
   return self.get_prep_value(value)

 File "/usr/local/lib/python2.7/dist-packages/Django-1.6.10-py2.7.egg/django/db/models/fields/__init__.py", line 613, in get_prep_value
   return int(value)

ValueError: invalid literal for int() with base 10: 'D-0031-02'


<WSGIRequest
path:/archives/items/D-0031-02/dc/,
GET:<QueryDict: {}>,
POST:<QueryDict: {}>,
COOKIES:{},
META:{u'CSRF_COOKIE': u's4qC1szrrxMxaHYI1fC3ag1f2bym2d1Q',
'DOCUMENT_ROOT': '/home/www/phono/',
'GATEWAY_INTERFACE': 'CGI/1.1',
'HTTP_ACCEPT': 'text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8',
'HTTP_ACCEPT_ENCODING': 'gzip,deflate',
'HTTP_CONNECTION': 'Keep-alive',
'HTTP_FROM': 'googlebot(at)googlebot.com',
```

When we change an Item's code, we get first an 404 error when saving the item : the redirection goes to the old url-code and not to the new one. Then we get the error indicated above.

**Comment by yomguy** [comment]
When a code is changed, it seems normal that the old URL becomes invalid.
If a code (=public_id) doesn't exist, Telemeta will try to reach it by its SQL id, then 404 if not found.

Here, your traceback shows that the google bot doesn't update its tables before scanning. If google is wrong there, the Telemeta behavior has been improved (returning a true 404 error) in 47186432fd9a199ff6a693a635fc7d247050054b so I think you might not be on the dev branch. As we are very close to the 1.6 release, you can go with it ;)

**Comment by AnasGhrab** [comment]
Ok. Thx ;)

Yes, I'm not on the Dev.. as the Telemeta-pages was not working anymore and I got error 500 on the Welcome page... I have to understand that better...

**Comment by yomguy** [comment]
Aren't the pages downloaded with:
```
git submodule foreach git pull origin master
git submodule update --init --recursive
```

**Comment by AnasGhrab** [comment]
Yes I do.

I close this issue as it seems that this problem is related to GoogleBot on items that do not exist anymore (code changes)...

**Comment by AnasGhrab** [comment]
Ah.. it is already closed :)

**Comment by yomguy** [comment]
indeed :)
