### ISSUE TITLE
URGENT: problème d'export csv

### ISSUE THREAD

**Issue by josimonnot** [Parisson/Telemeta#74]
ça ne marche pas:
http://archives.crem-cnrs.fr/playlists/143375692351340825/items/csv/
Bug?

**Comment by AnasGhrab** [comment]
Pareil ici aussi. L'export des collections fonctionne, mais pas celui des items.

**Comment by AnasGhrab** [comment]
Je ne peux plus « Lister » des items pour les retrouver sur le bureau... (avec la version 1.5.2 ?).
