### ISSUE TITLE
Bug sur une fiche Corpus du LAM

### ISSUE THREAD

**Issue by josimonnot** [Parisson/Telemeta#76]
http://telemeta.lam-ida.upmc.fr/archives/corpus/LAM_EVEN_04/
>
ValueError at /archives/corpus/LAM_EVEN_04/
The 'file' attribute has no file associated with it.

Certains items coincent aussi...

**Comment by AnasGhrab** [comment]
Je pense qu'il y a de forte chance que cela soit réglé avec à la mise à jour.

Par ailleurs, il est déconseillé de laisser la variable DEBUG = True (dans settings.py), car cela affiche en public des informations internes du serveur..

**Comment by yomguy** [comment]
fixed with the last "lam2" branch.

**Comment by josimonnot** [comment]
Super, merci pour Camille!
Et le LAM...
;-)
