### ISSUE TITLE
Bug sur une fiche Fonds du LAM

### ISSUE THREAD

**Issue by josimonnot** [Parisson/Telemeta#77]
http://telemeta.lam-ida.upmc.fr/archives/fonds/LAM_EVEN/

idem
Il semblerait que chaque fois que l'on fait une modif, ça bug!

**Comment by AnasGhrab** [comment]
Rajouter ou enlever quelque chose des médias associés du fonds résout-il momentanément le problème ?

**Comment by josimonnot** [comment]
la fonction "media associé" n'est plus accessible dans ce fonds!
Bizzare

**Comment by AnasGhrab** [comment]
Peut-être qu'elle n'existait pas dans la 1.4.5 ?

**Comment by josimonnot** [comment]
Si, il existe dans les fonds accessibles mais celui là est bloqué. 
Je vais attendre la MAJ IMMINENTE de Guillaume ;-)

**Comment by yomguy** [comment]
Fixed vith the last "lam2" branch
