### ISSUE TITLE
Moteur de recherche

### ISSUE THREAD

**Issue by josimonnot** [Parisson/Telemeta#79]
Le moteur simple ne marche plus pour les cotes: si on tape un cote, il n'y a pas de réponse.

**Comment by yomguy** [comment]
Arg, ça aurait dû être debugué depuis longtemps ça :'(
On va ajouter ça...

**Comment by josimonnot** [comment]
ça va plus vite dans google pour trouver une collection avec sa cote ;-)
On compte sur toi!
Bises

**Comment by yomguy** [comment]
ahaa, c'est déjà ça :)
ms oui je check ça dès aujourd'hui..

**Comment by AnasGhrab** [comment]
En fait, il trouve la côte quand elle est exact, mais pas quand c'est juste une succession de lettres : 

Il trouve : 
http://phonotheque.cmam.tn/haystack/?q=CD-187_rbaibiyya

Il ne trouve plus : 
http://phonotheque.cmam.tn/haystack/?q=CD-187

**Comment by yomguy** [comment]
Ah ok, merci de l'info !

**Comment by AnasGhrab** [comment]
Ça ne marche pas toujours... c'est étrange....

**Comment by yomguy** [comment]
Ca roule, ms avec la cote complète, pas partielle.
http://archives.crem-cnrs.fr/haystack/?q=CNRSMH_E_1959_002_004_001_27

**Comment by yomguy** [comment]
It works since the index is build from start.sh
