### ISSUE TITLE
Corpus et fonds dans la liste de résultats

### ISSUE THREAD

**Issue by josimonnot** [Parisson/Telemeta#81]
Quand on fait une recherche, la liste de résultats n'affiche que les items et les collections, on n'a plus les corpus et les fonds. Est-ce normal?
merci
J

**Comment by yomguy** [comment]
Selon ce qui a été fait sur le nouveau moteur, oui. Bizarre qu'n l'ait pas relevé pdt la phase de test !
A modifier donc...
