### ISSUE TITLE
html in collection description

### ISSUE THREAD

**Issue by AnasGhrab** [Parisson/Telemeta#87]
I'm trying to use html in the collection description. Normally I do that with adding ```| safe``` in a "description" field. I thought it should be in the collection_detail.html here : 
```
                {% if collection.description %}
                {% dl_field collection "description" %}
                {% endif %}
```
what are the ```dl_field``` ?

**Comment by yomguy** [comment]
pas sûr que dl_field laisse passer les balises:
https://github.com/Parisson/Telemeta/blob/master/telemeta/templatetags/telemeta_utils.py#L191

mieux vaut faire:
```
{% if collection.description %}
 <dt>{% trans "Description" %}</dt>
 <dd>{{ collection.description|html_line_break|safe }}</dd>
{% endif %}
```

comme là pour un autre champ:
https://github.com/Parisson/Telemeta/blob/master/telemeta/templates/telemeta/collection_detail.html#L186

**Comment by yomguy** [comment]
dl_field automatically retrieves and display the object field data with its name in the <dt><dd> frame.

**Comment by AnasGhrab** [comment]
Thx ;)
